routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','locked']], function () {
  // User dashboard
  Route::get('/', 'DashboardController@userDashboard')->name('user-dashboard');
  Route::get('dashboard', 'DashboardController@userDashboard')->name('user-dashboard');

  // Profile
  Route::get('/profiles/{user}/edit', 'ProfileController@editProfile')->name('profile-edit');
  Route::post('/profiles/{user}', 'ProfileController@updateProfile')->name('profile-update');
  Route::post('/profiles/{user}/reset', 'ProfileController@changePassword')->name('profile-reset');

  // Campaigns
  Route::resource('campaigns', 'CampaignController');

  // QRCode
  Route::get('qrcode/generate/{campaign}', 'QRCodeController@generateQRCode')->name('qrcode-generate');

  // coordinates
  Route::get('coordinates', 'DashboardController@getCoordinates')->name('get-coordinates');

  // Set read notification
  Route::post('notifications/read', 'DashboardController@readNotification');

  Route::group(['middleware' => ['permission:user_manage'], 'prefix' => 'admin'], function () {
    // Roles
    Route::resource('roles', 'Admin\RoleController');

    // Users
    Route::resource('users', 'Admin\UserController');
    Route::post('users/setlock', 'Admin\UserController@setLock');

    // Notifications
    Route::resource('notifications', 'Admin\NotificationController');
    Route::post('notifications/status', 'Admin\NotificationController@setStatus');

    // Admin dashboard
    Route::get('/', 'Admin\DashboardController@adminDashboard');
    Route::post('campaigns/delete', 'CampaignController@ajaxDelete');
  });
});

// Locked page
Route::get('locked', 'HomeController@lockedPage');

// QR code track
Route::get('qrcode/track/{campaign}', 'QRCodeController@qrcodeTrack')->name('qrcode-track');

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Models/Campaign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    /**
     * @var string
     */
    protected $table = 'campaigns';

    /**
     * @var array
     */
    protected $fillable = [
        'user_id',
        'campaign_name',
        'url',
        'foreground',
        'background',
        'logo'
    ];

    /**
     * @var array
     */
    protected $casts = [
        'user_id' => 'int',
        'campaign_name' => 'string',
        'url' => 'string',
        'foreground' => 'string',
        'background' => 'string',
        'logo' => 'string'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::Class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function campaignHits()
    {
        return $this->hasMany(CampaignHit::Class);
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Campaign;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\JsonResponse;

class CampaignController extends Controller
{
    // Default pageConfig
    protected $pageConfigs = [
        'navbarType' => 'sticky',
        'footerType' => 'static'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $campaigns = Auth::user()->campaigns;
        $breadcrumbs = [
            ['link'=>"",'name'=>trans('locale.campaign.title')], ['name'=>trans('locale.campaign.list')]
        ];
        return view('/pages/campaigns/index', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'campaigns' => $campaigns
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = [
            ['link'=>"",'name'=>trans('locale.campaign.title')], ['name'=>trans('locale.campaign.create')]
        ];

        return view('/pages/campaigns/create', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'campaign_name' => 'required|string|max:190',
            'url' => "required|url",
        ]);

        $logoPath = null;
        if ($request->hasFile('logo')) {
            $logoPath = $request->file('logo')->store('logos', 'public');
        }

        $campaign = $request->user()->campaigns()->create([
            'campaign_name' => $request->campaign_name,
            'url' => $request->url,
            'foreground' => $request->foreground,
            'background' => $request->background,
            'logo' => $logoPath
        ]);

        return redirect()
            ->route('campaigns.show', $campaign->id)
            ->with('message', trans('locale.campaign.saveSuccess'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function show(Campaign $campaign)
    {
        $breadcrumbs = [
            ['link'=>"",'name'=>trans('locale.campaign.title')], ['name'=>trans('locale.campaign.view')]
        ];
        return view('/pages/campaigns/view', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'campaign' => $campaign
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Campaign $campaign)
    {
        $campaign->delete();

        return redirect()
            ->route('campaigns.index')
            ->with('message', trans('locale.campaign.deleteSuccess'));
    }

    /**
     * Remove the specified resource from storage via ajax.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajaxDelete(Request $request)
    {
        $campaign = Campaign::findOrfail($request->campaign_id);
        $campaign->delete();

        return new JsonResponse(null, 204);
    }
}

resources/views/pages/campaigns/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.campaign.create'))

@section('page-style')
	<style>
		.color-picker {
			padding-top: 2px;
			padding-bottom: 2px;
			padding-left: 4px;
			padding-right: 4px;
		}
	</style>
@endsection

@section('content')
	<!-- Start Campaign -->
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
				<h4 class="card-title">@lang('locale.campaign.details')</h4>
				</div>
				<div class="card-content">
				<div class="card-body">
					<form action="/campaigns" method="POST" enctype="multipart/form-data">
						@csrf
						<fieldset class="form-group">
							<label for="campaign_name">@lang('locale.campaign.field.name')</label>
							<input name="campaign_name" type="text" class="form-control" id="campaignName" placeholder="@lang('locale.campaign.field.namePlace')" value="{{ old('campaign_name') }}">
							<span class="danger">{{ $errors->first('campaign_name') }}</span>
						</fieldset>

						<fieldset class="form-group">
							<label for="url">@lang('locale.campaign.field.url')</label>
							<input name="url" type="text" class="form-control" id="url" placeholder="@lang('locale.campaign.field.urlPlace')" value="{{ old('url') }}">
							<span class="danger">{{ $errors->first('url') }}</span>
						</fieldset>

						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-12">
								<fieldset class="form-group">
									<label for="foreground">@lang('locale.campaign.field.foreground')</label>
									<input type="color" id="foreground" name="foreground" class="form-control color-picker" value="{{ old('foreground') ?? '#000000' }}">
								</fieldset>

								<fieldset class="form-group">
									<label for="background">@lang('locale.campaign.field.background')</label>
									<input type="color" id="background" name="background" class="form-control color-picker" value="{{ old('background') ?? '#ffffff' }}">
								</fieldset>
							</div>

							<div class="col-lg-6 col-md-6 col-sm-12">
								<div class="form-group">
									<img src="{{ asset('images/default.png') }}" id="imgLogo" class="rounded mr-75" alt="logo image" height="140">
									<div class="mt-75">
										<div class="col-12 px-0 d-flex flex-sm-row flex-column justify-content-start">
											<label class="btn btn-sm btn-primary ml-50 mb-50 mb-sm-0 cursor-pointer waves-effect waves-light" for="logo">@lang('locale.campaign.field.uploadLogo')</label>
											<input type="file" id="logo" name="logo" onchange="previewLogo()" hidden="" accept="image/png, image/jpeg">
											<a href="javascript:resetLogo();" class="btn btn-sm btn-outline-warning ml-50 waves-effect waves-light">@lang('locale.campaign.reset')</a>
										</div>
										<p class="text-muted ml-75 mt-50"><small>@lang('locale.campaign.allow')</small></p>
									</div>
								</div>
							</div>
						</div>

						<div class="form-group d-flex justify-content-between align-items-center">
							<div class="text-left">
								<a href="/campaigns" class="card-link">@lang('locale.campaign.previous')</a>
							</div>
							<div class="text-right">
								<button class="btn btn-primary">@lang('locale.campaign.create')</button>
							</div>
						</div>
					</form>
				</div>
				</div>
			</div>
		</div>
	</div>
	<!--/ Start Campaign -->
@endsection

@section('page-script')
	<script>
		var defaultLogo = "{{ asset('images/default.png') }}";
		// logo preview
		function previewLogo() {
			var file = $('#logo')[0].files[0];
			if (file) {
				$("#imgLogo").attr("src", URL.createObjectURL(file));
			} else {
				$("#imgLogo").attr("src", defaultLogo);
			}
		}

		// logo remove and set default logo
		function resetLogo() {
			$("#imgLogo").attr("src", defaultLogo);
		}
	</script>
@endsection

resources/views/pages/campaigns/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.campaign.list'))

@section('vendor-style')
	{{-- vendor css files --}}
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
@endsection

@section('page-style')
	<style>
		.custom-select {
			height: auto;
		}

		.color-picker {
			padding-top: 2px;
			padding-bottom: 2px;
			padding-left: 4px;
			padding-right: 4px;
		}
	</style>
@endsection

@section('content')
	@if (session()->get('message'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<p class="mb-0">
			{{ session()->get('message') }}
		</p>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<!-- Start Campaign -->
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">@lang('locale.campaign.details')</h4>
		</div>
		<div class="card-content">
			<div class="card-body">
				<div class="table-responsive">
					<table id="campaignTable" class="table table-striped">
						<thead>
							<tr>
								<th>@lang('locale.id')</th>
								<th>@lang('locale.campaign.field.name')</th>
								<th>@lang('locale.campaign.field.url')</th>
								<th>@lang('locale.campaign.field.foreground')</th>
								<th>@lang('locale.campaign.field.background')</th>
								<th>@lang('locale.campaign.logo')</th>
								<th>@lang('locale.CreatedAt')</th>
								<th>@lang('locale.Actions')</th>
							</tr>
						</thead>
						<tbody>
							@foreach($campaigns as $campaign)
							<tr>
								<td>{{ $campaign->id }}</td>
								<td>{{ $campaign->campaign_name }}</td>
								<td>{{ $campaign->url }}</td>
								<td>
									<input type="color" class="form-control color-picker" disabled value="{{ $campaign->foreground }}">
								</td>
								<td>
									<input type="color" class="form-control color-picker" disabled value="{{ $campaign->background }}">
								</td>
								<td>
									@if($campaign->logo == null)
									<img src='{{ asset("images/default.png") }}' width="50">
									@else
									<img src='{{ asset("storage/$campaign->logo") }}' width="50">
									@endif
								</td>
								<th>{{ $campaign->created_at }}</th>
								<td>
									<form id="deleteForm{{ $campaign->id }}" action="{{ route('campaigns.destroy', $campaign->id) }}" method="POST" style="display: none;">
										@csrf
										@method('DELETE')
									</form>
									<a href="{{ route('campaigns.show', $campaign->id) }}" class="btn btn-icon rounded-circle btn-flat-success waves-effect waves-light">
										<i class="feather icon-eye"></i>
									</a>
									<a href="javascript:deleteCampaign({{ $campaign->id }})" class="btn btn-icon rounded-circle btn-flat-danger waves-effect waves-light">
										<i class="users-delete-icon feather icon-trash-2"></i>
									</a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<!--/ Start Campaign -->
@endsection

@section('vendor-script')
	{{-- vendor files --}}
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$('#campaignTable').DataTable();
		});

		function deleteCampaign(campaignId) {
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!',
				confirmButtonClass: 'btn btn-primary',
				cancelButtonClass: 'btn btn-danger ml-1',
				buttonsStyling: false,
			}).then(function (result) {
				if (result.value) {
					$('#deleteForm'+campaignId).submit();
				}
			})
		}
	</script>
@endsection

resources/views/pages/campaigns/view.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.campaign.view'))

@section('page-style')
	<style>
		.color-picker {
			padding-top: 2px;
			padding-bottom: 2px;
			padding-left: 4px;
			padding-right: 4px;
		}
	</style>
@endsection

@section('content')
	@if (session()->get('message'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<p class="mb-0">
			{{ session()->get('message') }}
		</p>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<!-- Start Campaign -->
	<div class="row">
		<div class="col-lg-8 col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
				<h4 class="card-title">@lang('locale.campaign.details')</h4>
				</div>
				<div class="card-content">
				<div class="card-body">
					<fieldset class="form-group">
						<label for="campaign_name">@lang('locale.campaign.field.name')</label>
						<input name="campaign_name" type="text" class="form-control" id="campaignName" readonly="readonly" value="{{ $campaign->campaign_name }}">
					</fieldset>

					<fieldset class="form-group">
						<label for="url">@lang('locale.campaign.field.url')</label>
						<input name="url" type="text" class="form-control" id="url" readonly="readonly" value="{{ $campaign->url }}">
					</fieldset>

					<fieldset class="form-group">
						<label for="foreground">@lang('locale.campaign.field.foreground')</label>
						<input type="color" id="foreground" name="foreground" class="form-control color-picker" disabled value="{{ $campaign->foreground }}">
					</fieldset>

					<fieldset class="form-group">
						<label for="background">@lang('locale.campaign.field.background')</label>
						<input type="color" id="background" name="background" class="form-control color-picker" disabled value="{{ $campaign->background }}">
					</fieldset>

					<div class="form-group d-flex justify-content-between align-items-center">
						<div class="text-left">
							<a href="/campaigns" class="card-link">@lang('locale.campaign.previous')</a>
						</div>
					</div>
				</div>
				</div>
			</div>
		</div>

		<div class="col-lg-4 col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
				<h4 class="card-title">@lang('locale.QRCode')</h4>
				</div>
				<div class="card-content">
					<div class="card-body">
						<div class="row">
							<div class="col-md-12 text-center">
								<img src="{!! url('/qrcode/generate', $campaign->id) !!}" id="qrcode" width="100%" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--/ Start Campaign -->
@endsection

@section('page-script')
  <script>
    $(document).ready(function() {
      {{--$.ajax({--}}
      {{--  url: "{{ url('/qrcode/generate', $campaign->id) }}",--}}
      {{--  type: 'GET',--}}
      {{--  data: {--}}
      {{--  },--}}
      {{--  dataType: "text",--}}
      {{--  success : function (data, status, jqXhr) {--}}
      {{--    console.log(data);--}}
      {{--    $("#qrcode").attr("src", data);--}}
      {{--  }--}}
      {{--});--}}
    });
  </script>
@endsection