routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','locked']], function () {
  // User dashboard
  Route::get('/', 'DashboardController@userDashboard')->name('user-dashboard');
  Route::get('dashboard', 'DashboardController@userDashboard')->name('user-dashboard');

  // Profile
  Route::get('/profiles/{user}/edit', 'ProfileController@editProfile')->name('profile-edit');
  Route::post('/profiles/{user}', 'ProfileController@updateProfile')->name('profile-update');
  Route::post('/profiles/{user}/reset', 'ProfileController@changePassword')->name('profile-reset');

  // Campaigns
  Route::resource('campaigns', 'CampaignController');

  // QRCode
  Route::get('qrcode/generate/{campaign}', 'QRCodeController@generateQRCode')->name('qrcode-generate');

  // coordinates
  Route::get('coordinates', 'DashboardController@getCoordinates')->name('get-coordinates');

  // Set read notification
  Route::post('notifications/read', 'DashboardController@readNotification');

  Route::group(['middleware' => ['permission:user_manage'], 'prefix' => 'admin'], function () {
    // Roles
    Route::resource('roles', 'Admin\RoleController');

    // Users
    Route::resource('users', 'Admin\UserController');
    Route::post('users/setlock', 'Admin\UserController@setLock');

    // Notifications
    Route::resource('notifications', 'Admin\NotificationController');
    Route::post('notifications/status', 'Admin\NotificationController@setStatus');

    // Admin dashboard
    Route::get('/', 'Admin\DashboardController@adminDashboard');
    Route::post('campaigns/delete', 'CampaignController@ajaxDelete');
  });
});

// Locked page
Route::get('locked', 'HomeController@lockedPage');

// QR code track
Route::get('qrcode/track/{campaign}', 'QRCodeController@qrcodeTrack')->name('qrcode-track');

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Models\Notification;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'email', 'password', 'photo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * set password attribute
     * @param String  $password
     */
    public function setPasswordAttribute($password)
    {   
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function campaigns()
    {
        return $this->hasMany(Campaign::Class);
    }

    public function readNotifications()
    {
        return $this->belongsToMany(Notification::class, 'user_notification');
    }

    public function notReadNotifications()
    {
        $readNotifications = $this->readNotifications()->pluck('id')->toArray();

        return Notification::whereNotIn('id', $readNotifications)
            ->where('status', 0)
            ->get();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Http\JsonResponse;

class UserController extends Controller
{
    // Default pageConfig
    protected $pageConfigs = [
        'navbarType' => 'sticky',
        'footerType' => 'static',
        'mainLayoutType' => 'horizontal',
        'horizontalMenuType' => 'floating',
        'theme' => 'dark',
        'navbarColor' => 'bg-primary'
    ];

    public function __construct() {
        // $this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all(); //Get all users
        $breadcrumbs = [
            ['link'=>"/admin/users", 'name'=>trans('locale.user.title')], ['name'=>trans('locale.user.list')]
        ];

        return view('/pages/admin/users/index', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all(); //Get all roles
        $breadcrumbs = [
            ['link'=>"/admin/users",'name'=>trans('locale.user.title')], ['name'=>trans('locale.user.create')]
        ];
        
        return view('/pages/admin/users/create', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:120',
            'surname'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:6'
        ]);

        $user = User::create($request->all()); //Retrieving only the email and password data

        $roles = $request->roles; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {
            $user->assignRole($roles); //Assigning role to user
        }        
        //Redirect to the users.index view and display message
        return redirect()->route('users.index')
            ->with('message', trans('locale.user.message.save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Spatie\Permission\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all(); //Get all roles

        $breadcrumbs = [
            ['link'=>"/admin/users",'name'=>trans('locale.user.title')], ['name'=>trans('locale.user.edit')]
        ];
        
        return view('/pages/admin/users/edit', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'roles' => $roles,
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Spatie\Permission\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name'=>'required|max:120',
            'surname'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$user->id,
        ]);

        $user->update($request->all());
        $roles = $request->roles;

        if (isset($roles)) {
            $user->syncRoles($roles);
        } else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        
        return redirect()->route('users.index')
            ->with('message', trans('locale.user.message.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Spatie\Permission\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()
            ->route('users.index')
            ->with('message', trans('locale.user.message.delete'));
    }

    /**
     * Set user lock, the default user has 0 as islocked field.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function setLock(Request $request)
    {
        $user = User::findOrfail($request->user_id);
        $user->islocked = $request->state;
        $user->save();

        return new JsonResponse(null, 204);
    }
}

resources/views/pages/admin/users/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.user.create'))

@section('vendor-style')
	<!-- vendor css files -->
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
	<style>
		.select2-selection__choice {
			background-color: #7567F1 !important;
			color: white !important;
			border-color: #7567F1 !important;
		}
	</style>
@endsection

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.user.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('users.store') }}" method="POST">
				@csrf
				<fieldset class="form-group">
					<label for="name">@lang('locale.Name')*</label>
					<input name="name" type="text" class="form-control" id="name" placeholder="@lang('locale.Name')" value="{{ old('name') }}">
					<span class="danger">{{ $errors->first('name') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="surname">@lang('locale.Surname')*</label>
					<input name="surname" type="text" class="form-control" id="surname" placeholder="@lang('locale.Surname')" value="{{ old('surname') }}">
					<span class="danger">{{ $errors->first('surname') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="email">@lang('locale.Email')*</label>
					<input name="email" type="email" class="form-control" id="email" placeholder="@lang('locale.Email')" value="{{ old('email') }}">
					<span class="danger">{{ $errors->first('email') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="password">@lang('locale.Password')*</label>
					<input name="password" type="password" class="form-control" id="password" placeholder="@lang('locale.Password')" value="{{ old('password') }}">
					<span class="danger">{{ $errors->first('password') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="roles">@lang('locale.role.title')*</label>
					<select name="roles[]" class="select2 form-control" multiple="multiple">
						@foreach ($roles as $role)
						<option value="{{ $role->name }}">{{ $role->name }}</option>
						@endforeach
					</select>
					<span class="danger">{{ $errors->first('roles') }}</span>
				</fieldset>

				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.user.create')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	<!-- vendor files -->
	<script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$(".select2").select2({
				// the following code is used to disable x-scrollbar when click in select input and
				// take 100% width in responsive also
				dropdownAutoWidth: true,
				width: '100%'
			 });
		});
	</script>
@endsection

resources/views/pages/admin/users/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.user.edit'))

@section('vendor-style')
	<!-- vendor css files -->
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
	<style>
		.select2-selection__choice {
			background-color: #7567F1 !important;
			color: white !important;
			border-color: #7567F1 !important;
		}
	</style>
@endsection

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.user.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('users.update', $user->id) }}" method="POST">
				@csrf
				@method('PUT')
				<fieldset class="form-group">
					<label for="name">@lang('locale.Name')*</label>
					<input name="name" type="text" class="form-control" id="name" placeholder="@lang('locale.Name')" value="{{ $user->name }}">
					<span class="danger">{{ $errors->first('name') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="surname">@lang('locale.Surname')*</label>
					<input name="surname" type="text" class="form-control" id="surname" placeholder="@lang('locale.Surname')" value="{{ $user->surname }}">
					<span class="danger">{{ $errors->first('surname') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="email">@lang('locale.Email')*</label>
					<input name="email" type="email" class="form-control" id="email" placeholder="@lang('locale.Email')" value="{{ $user->email }}">
					<span class="danger">{{ $errors->first('email') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="password">@lang('locale.Password')*</label>
					<input name="password" type="password" class="form-control" id="password" placeholder="@lang('locale.Password')" value="{{ old('password') }}">
					<span class="danger">{{ $errors->first('password') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="name">@lang('locale.role.title')*</label>
					<select name="roles[]" class="select2 form-control" multiple="multiple">
						@php
						$arrRoles = $user->roles->pluck("name")->toArray();
						@endphp
						@foreach ($roles as $role)
						<option value="{{ $role->name }}" {{ in_array($role->name, $arrRoles) ? "selected" : "" }} >{{ $role->name }}</option>
						@endforeach
					</select>
					<span class="danger">{{ $errors->first('roles') }}</span>
				</fieldset>

				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.user.update')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	<!-- vendor files -->
	<script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$(".select2").select2({
				// the following code is used to disable x-scrollbar when click in select input and
				// take 100% width in responsive also
				dropdownAutoWidth: true,
				width: '100%'
			 });
		});
	</script>
@endsection

resources/views/pages/admin/users/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.user.list'))

@section('vendor-style')
	{{-- vendor css files --}}
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/toastr.css')) }}">
@endsection


@section('page-style')
	<style>
		.custom-select {
			height: auto;
		}
	</style>
@endsection

@section('content')
	@if (session()->get('message'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<p class="mb-0">
			{{ session()->get('message') }}
		</p>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<div class="card">
		<div class="card-header">
			<a href="{{ route('users.create') }}" class="btn btn-primary mr-1 mb-1 waves-effect waves-light"><i class="fa fa-plus"></i> @lang('locale.user.create')</a>
		</div>
		<div class="card-content">
			<div class="card-body">
				<div class="table-responsive">
					<table id="userTable" class="table table-striped">
						<thead>
							<tr>
								<th>@lang('locale.id')</th>
								<th>@lang('locale.Username')</th>
								<th>@lang('locale.Email')</th>
								<th>@lang('locale.role.title')</th>
								<th>@lang('locale.user.lock')</th>
								<th>@lang('locale.CreatedAt')</th>
								<th>@lang('locale.UpdatedAt')</th>
								<th>@lang('locale.Actions')</th>
							</tr>
						</thead>
						<tbody>
							@foreach($users as $user)
							<tr>
								<td>{{ $user->id }}</td>
								<td>
									@if ($user->photo === null)
									<span class="avatar"><img src="{{ asset('/images/avatar.png') }}" height="32" width="32"></span>
									@else
									<span class="avatar"><img src="{{ asset('storage/' . $user->photo) }}" height="32" width="32"></span>
									@endif
									{{ $user->name }} {{ $user->surname }}
								</td>
								<td>{{ $user->email }}</td>
								<td>
									@foreach($user->roles as $role)
									<div class="badge badge-primary">{{ $role->name }}</div>
									@endforeach
								</td>
								<td>
									<div class="custom-control custom-switch custom-switch-danger switch-lg mr-2">
										<input id="locked_{{ $user->id }}" class="custom-control-input" type="checkbox" {{ $user->islocked == 1 ? "checked" : "" }} onchange="lockUser(this.checked, {{ $user->id }})" {{ Auth::user()->id == $user->id || $user->id == 1 ? "disabled" : "" }}>
										<label class="custom-control-label" for="locked_{{ $user->id }}">
											<span class="switch-text-left">Locked</span>
											<span class="switch-text-right">Unlocked</span>
										</label>
									</div>
							  	</td>
								<th>{{ $user->created_at }}</th>
								<th>{{ $user->updated_at }}</th>
								<td>
									<form id="deleteForm{{ $user->id }}" action="{{ route('users.destroy', $user->id) }}" method="POST" style="display: none;">
										@csrf
										@method('DELETE')
									</form>
									<a href="{{ route('users.edit', $user->id) }}" class="btn btn-icon rounded-circle btn-flat-success waves-effect waves-light">
										<i class="feather icon-edit"></i>
									</a>
									@if (Auth::user()->id != $user->id && $user->id != 1)
									<a href="javascript:deleteUser({{ $user->id }})" class="btn btn-icon rounded-circle btn-flat-danger waves-effect waves-light">
										<i class="feather icon-trash-2"></i>
									</a>
									@endif
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	{{-- vendor files --}}
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/toastr.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$('#userTable').DataTable();

			$.ajaxSetup({
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}
			});
		});

		function deleteUser(userId) {
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!',
				confirmButtonClass: 'btn btn-primary',
				cancelButtonClass: 'btn btn-danger ml-1',
				buttonsStyling: false,
			}).then(function (result) {
				if (result.value) {
					$('#deleteForm'+userId).submit();
				}
			})
		}

		function lockUser(state, user_id) {
			$.ajax({
				url: "{{ url('/admin/users/setlock') }}",
				type: 'POST',
				data: {
					state : state ? 1 : 0,
					user_id: user_id
				},
				dataType: "JSON",
				success : function (data, status, jqXhr) {
					if (jqXhr.status === 204) {
						toastr.success('That user status is changed successfully.', 'Notification', {
							"showMethod": "fadeIn",
							"hideMethod": "fadeOut",
							"closeButton": true,
							"progressBar": true,
							timeOut: 2000
						});
					}
				}
			});
		}
	</script>
@endsection