routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','locked']], function () {
  // User dashboard
  Route::get('/', 'DashboardController@userDashboard')->name('user-dashboard');
  Route::get('dashboard', 'DashboardController@userDashboard')->name('user-dashboard');

  // Profile
  Route::get('/profiles/{user}/edit', 'ProfileController@editProfile')->name('profile-edit');
  Route::post('/profiles/{user}', 'ProfileController@updateProfile')->name('profile-update');
  Route::post('/profiles/{user}/reset', 'ProfileController@changePassword')->name('profile-reset');

  // Campaigns
  Route::resource('campaigns', 'CampaignController');

  // QRCode
  Route::get('qrcode/generate/{campaign}', 'QRCodeController@generateQRCode')->name('qrcode-generate');

  // coordinates
  Route::get('coordinates', 'DashboardController@getCoordinates')->name('get-coordinates');

  // Set read notification
  Route::post('notifications/read', 'DashboardController@readNotification');

  Route::group(['middleware' => ['permission:user_manage'], 'prefix' => 'admin'], function () {
    // Roles
    Route::resource('roles', 'Admin\RoleController');

    // Users
    Route::resource('users', 'Admin\UserController');
    Route::post('users/setlock', 'Admin\UserController@setLock');

    // Notifications
    Route::resource('notifications', 'Admin\NotificationController');
    Route::post('notifications/status', 'Admin\NotificationController@setStatus');

    // Admin dashboard
    Route::get('/', 'Admin\DashboardController@adminDashboard');
    Route::post('campaigns/delete', 'CampaignController@ajaxDelete');
  });
});

// Locked page
Route::get('locked', 'HomeController@lockedPage');

// QR code track
Route::get('qrcode/track/{campaign}', 'QRCodeController@qrcodeTrack')->name('qrcode-track');

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    // Default pageConfig
    protected $pageConfigs = [
        'navbarType' => 'sticky',
        'footerType' => 'static',
        'mainLayoutType' => 'horizontal',
        'horizontalMenuType' => 'floating',
        'theme' => 'dark',
        'navbarColor' => 'bg-primary'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        // $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
        // $this->middleware('permission:role-admin');
        // $this->middleware('permission:role-create', ['only' => ['create','store']]);
        // $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        // $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all(); //Get all roles
        $breadcrumbs = [
            ['link'=>"/admin/roles", 'name'=>trans('locale.role.title')], ['name'=>trans('locale.role.list')]
        ];

        return view('/pages/admin/roles/index', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'roles' => $roles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all(); //Get all permissions
        $breadcrumbs = [
            ['link'=>"/admin/roles",'name'=>trans('locale.role.title')], ['name'=>trans('locale.role.create')]
        ];
        
        return view('/pages/admin/roles/create', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'permissions' => $permissions
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|unique:roles|max:10',
            'permissions' =>'required',
            ]
        );

        $permissions = $request->permissions;

        $role = Role::create([
            'name' => $request->name
        ]);
        
        if (isset($permissions)) {
            $role->givePermissionTo($permissions);
        }

        return redirect()
            ->route('roles.index')
            ->with('message', trans('locale.role.message.save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::get(); //Get all roles
        $breadcrumbs = [
            ['link'=>"/admin/roles",'name'=>trans('locale.role.title')], ['name'=>trans('locale.role.edit')]
        ];
        
        return view('/pages/admin/roles/edit', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'role' => $role,
            'permissions' => $permissions
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request, [
            'name'=>'required|max:10|unique:roles,name,'.$role->id,
            'permissions' =>'required',
        ]);
        
        $permissions = $request->permissions;

        $role->update([
            'name' => $request->name
        ]);
        
        $role->syncPermissions($permissions);

        return redirect()->route('roles.index')
            ->with('message', trans('locale.role.message.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()
            ->route('roles.index')
            ->with('message', trans('locale.role.message.delete'));
    }
}

resources/views/pages/admin/roles/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.role.create'))

@section('vendor-style')
	<!-- vendor css files -->
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
	<style>
		.select2-selection__choice {
			background-color: #7567F1 !important;
			color: white !important;
			border-color: #7567F1 !important;
		}
	</style>
@endsection

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.role.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('roles.store') }}" method="POST">
				@csrf
				<fieldset class="form-group">
					<label for="name">@lang('locale.role.name')*</label>
					<input name="name" type="text" class="form-control" id="name" placeholder="@lang('locale.role.name')" value="{{ old('name') }}">
					<span class="danger">{{ $errors->first('name') }}</span>
				</fieldset>

				<div class="form-group">
					<label for="permissions">@lang('locale.role.permissions')*</label>
					<select name="permissions[]" class="select2 form-control" multiple="multiple">
						@foreach ($permissions as $permission)
						<option value="{{ $permission->name }}">{{ $permission->name }}</option>
						@endforeach
					</select>
					<span class="danger">{{ $errors->first('permissions') }}</span>
				</div>

				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.role.create')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	<!-- vendor files -->
	<script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$(".select2").select2({
				// the following code is used to disable x-scrollbar when click in select input and
				// take 100% width in responsive also
				dropdownAutoWidth: true,
				width: '100%'
			 });
		});
	</script>
@endsection

resources/views/pages/admin/roles/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.role.edit'))

@section('vendor-style')
	<!-- vendor css files -->
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
	<style>
		.select2-selection__choice {
			background-color: #7567F1 !important;
			color: white !important;
			border-color: #7567F1 !important;
		}
	</style>
@endsection

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.role.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('roles.update', $role->id) }}" method="POST">
				@csrf
				@method('PUT')
				<fieldset class="form-group">
					<label for="name">@lang('locale.role.name')*</label>
					<input name="name" type="text" class="form-control" id="name" placeholder="@lang('locale.role.name')" value="{{ $role->name }}">
					<span class="danger">{{ $errors->first('name') }}</span>
				</fieldset>

				<fieldset class="form-group">
					<label for="name">@lang('locale.role.permissions')*</label>
					<select name="permissions[]" class="select2 form-control" multiple="multiple">
						@php
						$arrPermissions = $role->permissions->pluck("name")->toArray();
						@endphp
						@foreach ($permissions as $permission)
						<option value="{{ $permission->name }}" {{ in_array($permission->name, $arrPermissions) ? "selected" : "" }} >{{ $permission->name }}</option>
						@endforeach
					</select>
					<span class="danger">{{ $errors->first('permissions') }}</span>
				</fieldset>

				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.role.update')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	<!-- vendor files -->
	<script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$(".select2").select2({
				// the following code is used to disable x-scrollbar when click in select input and
				// take 100% width in responsive also
				dropdownAutoWidth: true,
				width: '100%'
			 });
		});
	</script>
@endsection

resources/views/pages/admin/roles/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.role.list'))

@section('vendor-style')
	{{-- vendor css files --}}
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
@endsection


@section('page-style')
	<style>
		.custom-select {
			height: auto;
		}
	</style>
@endsection

@section('content')
	@if (session()->get('message'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<p class="mb-0">
			{{ session()->get('message') }}
		</p>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<div class="card">
		<div class="card-header">
			<a href="{{ route('roles.create') }}" class="btn btn-primary mr-1 mb-1 waves-effect waves-light"><i class="fa fa-plus"></i> @lang('locale.role.create')</a>
		</div>
		<div class="card-content">
			<div class="card-body">
				<div class="table-responsive">
					<table id="roleTable" class="table table-striped">
						<thead>
							<tr>
								<th>@lang('locale.id')</th>
								<th>@lang('locale.role.name')</th>
								<th>@lang('locale.role.permissions')</th>
								<th>@lang('locale.CreatedAt')</th>
								<th>@lang('locale.UpdatedAt')</th>
								<th>@lang('locale.Actions')</th>
							</tr>
						</thead>
						<tbody>
							@foreach($roles as $role)
							<tr>
								<td>{{ $role->id }}</td>
								<td>{{ $role->name }}</td>
								<td>
									@foreach ($role->permissions as $permission)
									<div class="badge badge-primary">{{ $permission->name }}</div>
									@endforeach
								</td>
								<th>{{ $role->created_at }}</th>
								<th>{{ $role->updated_at }}</th>
								<td>
									<form id="deleteForm{{ $role->id }}" action="{{ route('roles.destroy', $role->id) }}" method="POST" style="display: none;">
										@csrf
										@method('DELETE')
									</form>
									<a href="{{ route('roles.edit', $role->id) }}" class="btn btn-icon rounded-circle btn-flat-success waves-effect waves-light">
										<i class="feather icon-edit"></i>
									</a>
									<a href="javascript:deleteRole({{ $role->id }})" class="btn btn-icon rounded-circle btn-flat-danger waves-effect waves-light">
										<i class="feather icon-trash-2"></i>
									</a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	{{-- vendor files --}}
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$('#roleTable').DataTable();
		});

		function deleteRole(roleId) {
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!',
				confirmButtonClass: 'btn btn-primary',
				cancelButtonClass: 'btn btn-danger ml-1',
				buttonsStyling: false,
			}).then(function (result) {
				if (result.value) {
					$('#deleteForm'+roleId).submit();
				}
			})
		}
	</script>
@endsection