routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','locked']], function () {
  // User dashboard
  Route::get('/', 'DashboardController@userDashboard')->name('user-dashboard');
  Route::get('dashboard', 'DashboardController@userDashboard')->name('user-dashboard');

  // Profile
  Route::get('/profiles/{user}/edit', 'ProfileController@editProfile')->name('profile-edit');
  Route::post('/profiles/{user}', 'ProfileController@updateProfile')->name('profile-update');
  Route::post('/profiles/{user}/reset', 'ProfileController@changePassword')->name('profile-reset');

  // Campaigns
  Route::resource('campaigns', 'CampaignController');

  // QRCode
  Route::get('qrcode/generate/{campaign}', 'QRCodeController@generateQRCode')->name('qrcode-generate');

  // coordinates
  Route::get('coordinates', 'DashboardController@getCoordinates')->name('get-coordinates');

  // Set read notification
  Route::post('notifications/read', 'DashboardController@readNotification');

  Route::group(['middleware' => ['permission:user_manage'], 'prefix' => 'admin'], function () {
    // Roles
    Route::resource('roles', 'Admin\RoleController');

    // Users
    Route::resource('users', 'Admin\UserController');
    Route::post('users/setlock', 'Admin\UserController@setLock');

    // Notifications
    Route::resource('notifications', 'Admin\NotificationController');
    Route::post('notifications/status', 'Admin\NotificationController@setStatus');

    // Admin dashboard
    Route::get('/', 'Admin\DashboardController@adminDashboard');
    Route::post('campaigns/delete', 'CampaignController@ajaxDelete');
  });
});

// Locked page
Route::get('locked', 'HomeController@lockedPage');

// QR code track
Route::get('qrcode/track/{campaign}', 'QRCodeController@qrcodeTrack')->name('qrcode-track');

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    /**
     * @var string
     */
    protected $table = 'notifications';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'text', 'status'
    ];

    public function readUsers()
    {
        return $this->belongsToMany(User::class, 'user_notification');
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

class NotificationController extends Controller
{
    // Default pageConfig
    protected $pageConfigs = [
        'navbarType' => 'sticky',
        'footerType' => 'static',
        'mainLayoutType' => 'horizontal',
        'horizontalMenuType' => 'floating',
        'theme' => 'dark',
        'navbarColor' => 'bg-primary'
    ];

    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = [
            ['link'=>"/admin/notifications", 'name'=>trans('locale.notification.title')], ['name'=>trans('locale.notification.list')]
        ];
        $notifications = Notification::all();

        return view('/pages/admin/notifications/index', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'notifications' => $notifications
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = [
            ['link'=>"/admin/notifications",'name'=>trans('locale.notification.title')], ['name'=>trans('locale.notification.create')]
        ];
        
        return view('/pages/admin/notifications/create', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'=>'required|max:90',
            'text'=>'required|max:190',
            'status'=>'required'
        ]);

        $user = Notification::create($request->all());

        return redirect()->route('notifications.index')
            ->with('message', trans('locale.notification.message.save'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Spatie\Permission\Models\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function edit(Notification $notification)
    {
        $breadcrumbs = [
            ['link'=>"/admin/notifications",'name'=>trans('locale.notification.title')], ['name'=>trans('locale.notification.edit')]
        ];
        
        return view('/pages/admin/notifications/edit', [
            'pageConfigs' => $this->pageConfigs,
            'breadcrumbs' => $breadcrumbs,
            'notification' => $notification
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Spatie\Permission\Models\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notification $notification)
    {
        $this->validate($request, [
            'title'=>'required|max:90',
            'text'=>'required|max:190',
            'status'=>'required'
        ]);

        $notification->update($request->all());
        
        return redirect()->route('notifications.index')
            ->with('message', trans('locale.notification.message.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Spatie\Permission\Models\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notification $notification)
    {
        $notification->delete();

        return redirect()
            ->route('notifications.index')
            ->with('message', trans('locale.notification.message.delete'));
    }

    /**
     * Set notification status, default status is 1.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function setStatus(Request $request)
    {
        $notification = Notification::findOrfail($request->notification_id);
        $notification->status = $request->state;
        $notification->save();

        return new JsonResponse(null, 204);
    }
}

resources/views/pages/admin/notifications/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.notification.create'))

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.notification.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('notifications.store') }}" method="POST">
				@csrf
				<fieldset class="form-group">
					<label for="title">@lang('locale.notification.name')*</label>
					<input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title" placeholder="@lang('locale.notification.name')" value="{{ old('title') }}">
					@error('title')
						<span class="invalid-feedback danger" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</fieldset>
				
				<fieldset class="form-group">
					<label for="text">@lang('locale.notification.text')*</label>
					<input name="text" type="text" class="form-control @error('text') is-invalid @enderror" id="text" placeholder="@lang('locale.notification.text')" value="{{ old('text') }}">
					@error('text')
					<span class="invalid-feedback danger" role="alert">
						<strong>{{ $message }}</strong>
						</span>
					@enderror
				</fieldset>

				<fieldset class="form-group">
					<label for="title">@lang('locale.notification.status')</label>
					<select name="status" class="custom-select" id="status">
						<option value="0" selected>Allowed</option>
						<option value="1">Denied</option>
					</select>
			  </fieldset>
				
				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.notification.save')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

resources/views/pages/admin/notifications/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.notification.edit'))

@section('content')
	<div class="card">
		<div class="card-header">
		<h4 class="card-title">@lang('locale.notification.details')</h4>
		</div>
		<div class="card-content">
		<div class="card-body">
			<form action="{{ route('notifications.update', $notification) }}" method="POST">
				@csrf
				@method('PUT')
				<fieldset class="form-group">
					<label for="title">@lang('locale.notification.name')*</label>
					<input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title" placeholder="@lang('locale.notification.name')" value="{{ $notification->title }}">
					@error('title')
						<span class="invalid-feedback danger" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</fieldset>
				
				<fieldset class="form-group">
					<label for="text">@lang('locale.notification.text')*</label>
					<input name="text" type="text" class="form-control @error('text') is-invalid @enderror" id="text" placeholder="@lang('locale.notification.text')" value="{{ $notification->text }}">
					@error('text')
					<span class="invalid-feedback danger" role="alert">
						<strong>{{ $message }}</strong>
						</span>
					@enderror
				</fieldset>

				<fieldset class="form-group">
					<label for="title">@lang('locale.notification.status')</label>
					<select name="status" class="custom-select" id="status">
						<option value="0" {{ $notification->status === 0 ? 'selected' : '' }}>Allowed</option>
						<option value="1" {{ $notification->status === 1 ? 'selected' : '' }}>Denied</option>
					</select>
			  </fieldset>
				
				<div class="text-right">
					<button class="btn btn-primary">@lang('locale.notification.save')</button>
				</div>
			</form>
		</div>
		</div>
	</div>
@endsection

resources/views/pages/admin/notifications/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', trans('locale.notification.list'))

@section('vendor-style')
	{{-- vendor css files --}}
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
	<link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/toastr.css')) }}">
@endsection

@section('page-style')
	<style>
		.custom-switch .custom-control-label:before {
			background-color: #28C76F !important;
		}
		.switch-text-right {
			color: white !important;
		}
	</style>
@endsection

@section('content')
	@if (session()->get('message'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<p class="mb-0">
			{{ session()->get('message') }}
		</p>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<div class="card">
		<div class="card-header">
			<a href="{{ route('notifications.create') }}" class="btn btn-primary mr-1 mb-1 waves-effect waves-light"><i class="fa fa-plus"></i> @lang('locale.notification.create')</a>
		</div>
		<div class="card-content">
			<div class="card-body">
				<div class="table-responsive">
					<table id="notificationTable" class="table table-striped">
						<thead>
							<tr>
								<th>@lang('locale.id')</th>
								<th>@lang('locale.notification.name')</th>
								<th>@lang('locale.notification.text')</th>
								<th>@lang('locale.notification.status')</th>
								<th>@lang('locale.CreatedAt')</th>
								<th>@lang('locale.UpdatedAt')</th>
								<th>@lang('locale.Actions')</th>
							</tr>
						</thead>
						<tbody>
							@foreach($notifications as $notification)
							<tr>
								<td>{{ $notification->id }}</td>
								<td>{{ $notification->title }}</td>
								<td>{{ $notification->text }}</td>
								<td>
									<div class="custom-control custom-switch custom-switch-danger switch-lg mr-2">
										<input id="locked_{{ $notification->id }}" class="custom-control-input" type="checkbox" {{ $notification->status == 1 ? "checked" : "" }} onchange="setStatus(this.checked, {{ $notification->id }})">
										<label class="custom-control-label" for="locked_{{ $notification->id }}">
											<span class="switch-text-left">Denied</span>
											<span class="switch-text-right">Allowed</span>
										</label>
									</div>
							  	</td>
								<th>{{ $notification->created_at }}</th>
								<th>{{ $notification->updated_at }}</th>
								<td>
									<form id="deleteForm{{ $notification->id }}" action="{{ route('notifications.destroy', $notification->id) }}" method="POST" style="display: none;">
										@csrf
										@method('DELETE')
									</form>
									<a href="{{ route('notifications.edit', $notification->id) }}" class="btn btn-icon rounded-circle btn-flat-success waves-effect waves-light">
										<i class="feather icon-edit"></i>
									</a>
									<a href="javascript:deleteNotification({{ $notification->id }})" class="btn btn-icon rounded-circle btn-flat-danger waves-effect waves-light">
										<i class="feather icon-trash-2"></i>
									</a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('vendor-script')
	{{-- vendor files --}}
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
	<script src="{{ asset(mix('vendors/js/extensions/toastr.min.js')) }}"></script>
@endsection

@section('page-script')
	<script>
		$(document).ready(function() {
			$('#notificationTable').DataTable();

			$.ajaxSetup({
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}
			});
		});

		function deleteNotification(notificationId) {
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!',
				confirmButtonClass: 'btn btn-primary',
				cancelButtonClass: 'btn btn-danger ml-1',
				buttonsStyling: false,
			}).then(function (result) {
				if (result.value) {
					$('#deleteForm'+notificationId).submit();
				}
			})
		}

		function setStatus(state, notificationId) {
			$.ajax({
				url: "{{ url('/admin/notifications/status') }}",
				type: 'POST',
				data: {
					state : state ? 1 : 0,
					notification_id: notificationId
				},
				dataType: "JSON",
				success : function (data, status, jqXhr) {
					if (jqXhr.status === 204) {
						toastr.success('That notification status is changed successfully.', 'Notification', {
							"showMethod": "fadeIn",
							"hideMethod": "fadeOut",
							"closeButton": true,
							"progressBar": true,
							timeOut: 2000
						});
					}
				}
			});
		}
	</script>
@endsection